#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LEDMATRIXCONTROLLER.Resource", IsApplication=true)]

namespace LEDMATRIXCONTROLLER
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int sports_array = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int tsquare_dayBackground = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int tsquare_dayTextColor = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int tsquare_displayHeader = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int tsquare_dividerColor = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int tsquare_headerTextColor = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int tsquare_state_current_month = 2130771975;
			
			// aapt resource value: 0x7f01000c
			public const int tsquare_state_highlighted = 2130771980;
			
			// aapt resource value: 0x7f010009
			public const int tsquare_state_range_first = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int tsquare_state_range_last = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int tsquare_state_range_middle = 2130771978;
			
			// aapt resource value: 0x7f010006
			public const int tsquare_state_selectable = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int tsquare_state_today = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int tsquare_titleTextColor = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_active_month_bg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int calendar_bg = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int calendar_divider = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int calendar_highlighted_day_bg = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_inactive_month_bg = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int calendar_selected_day_bg = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int calendar_selected_range_bg = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int calendar_text_active = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int calendar_text_highlighted = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int calendar_text_inactive = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int calendar_text_selected = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int calendar_text_selector = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int calendar_text_unselectable = 2131099659;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_day_headers_paddingbottom = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int calendar_month_title_bottommargin = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int calendar_month_topmargin = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int calendar_text_medium = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_text_small = 2131165188;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendar_bg_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int connect_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drop_down_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int round_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int spinner_text = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int text_field = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080014
			public const int btn_resolution = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int btn_send_date = 2131230741;
			
			// aapt resource value: 0x7f080002
			public const int btn_set_date = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int btn_set_time = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int calendar_grid = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int connect_button = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int date_picker = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int day_view_adapter_class = 2131230720;
			
			// aapt resource value: 0x7f080013
			public const int edit_text_date = 2131230739;
			
			// aapt resource value: 0x7f08000b
			public const int img_btn_1 = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int list_of_bluetooth_spinner = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int list_of_bluetooth_text_view = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int password_text = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int password_textview = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int relativeLayout1 = 2131230725;
			
			// aapt resource value: 0x7f08000f
			public const int seek_bar_brightness = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int seek_bar_speed = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int spn_resolution = 2131230738;
			
			// aapt resource value: 0x7f080003
			public const int time_picker = 2131230723;
			
			// aapt resource value: 0x7f08000c
			public const int title = 2131230732;
			
			// aapt resource value: 0x7f080017
			public const int txt_brightness = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int txt_resolution = 2131230737;
			
			// aapt resource value: 0x7f080016
			public const int txt_set_date = 2131230742;
			
			// aapt resource value: 0x7f08000e
			public const int txt_speed = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DateAndTime = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int month = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Settings = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int week = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_arrow_drop_down_black_24dp = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_chevron_right_black_24dp = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_date_range_black_24dp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_lock_outline_black_24dp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_refresh_black_24dp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_settings_black_24dp = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Icon = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings_Icon = 2130903047;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int day_name_format = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int hello = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int invalid_date = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int month_name_format = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int CalendarCell = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int CalendarCell_CalendarDate = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int CalendarCell_DayHeader = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int CalendarTitle = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int button_text = 2131296260;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CalendarPickerView = new int[] {
					16842964,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int CalendarPickerView_android_background = 0;
			
			// aapt resource value: 2
			public const int CalendarPickerView_tsquare_dayBackground = 2;
			
			// aapt resource value: 3
			public const int CalendarPickerView_tsquare_dayTextColor = 3;
			
			// aapt resource value: 5
			public const int CalendarPickerView_tsquare_displayHeader = 5;
			
			// aapt resource value: 1
			public const int CalendarPickerView_tsquare_dividerColor = 1;
			
			// aapt resource value: 6
			public const int CalendarPickerView_tsquare_headerTextColor = 6;
			
			// aapt resource value: 4
			public const int CalendarPickerView_tsquare_titleTextColor = 4;
			
			public static int[] calendar_cell = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int calendar_cell_tsquare_state_current_month = 1;
			
			// aapt resource value: 6
			public const int calendar_cell_tsquare_state_highlighted = 6;
			
			// aapt resource value: 3
			public const int calendar_cell_tsquare_state_range_first = 3;
			
			// aapt resource value: 5
			public const int calendar_cell_tsquare_state_range_last = 5;
			
			// aapt resource value: 4
			public const int calendar_cell_tsquare_state_range_middle = 4;
			
			// aapt resource value: 0
			public const int calendar_cell_tsquare_state_selectable = 0;
			
			// aapt resource value: 2
			public const int calendar_cell_tsquare_state_today = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
