#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LEDMATRIXCONTROLLER.Resource", IsApplication=true)]

namespace LEDMATRIXCONTROLLER
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int sports_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int connect_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drop_down_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int spinner_text = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int text_field = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int btn_resolution = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int connect_button = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int img_btn_1 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout1 = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int list_of_bluetooth_spinner = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int list_of_bluetooth_text_view = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int password_text = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int password_textview = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int seek_bar_brightness = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int seek_bar_speed = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int spn_resolution = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int txt_brightness = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int txt_speed = 2131230733;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_arrow_drop_down_black_24dp = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_chevron_right_black_24dp = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_lock_outline_black_24dp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_refresh_black_24dp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_settings_black_24dp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Icon = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Settings_Icon = 2130903046;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
